version: '3'

services: 
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: ayrtonsouza/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: ayrtonsouza/nginx:prod
    container_net: nginx
    networks:
      - laranet
    ports: 
      - "8080:80"

networks:
  laranet
    driver: bridge